services:
  mongonet:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  mainservicenet:
    image: thattallman/mainservice:latest
    ports:
      - "8001:8001"
  publicservicenet:
    image: thattallman/publicservice:latest
    ports:
      - "8000:8000"
volumes:
  mongodb_data:
